[package]
name = "app-wasmtime"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = { version = "43.0.1", default-features = false, features = ["std", "component-model", "runtime", "custom-virtual-memory", "custom-native-signals"] }
wasmtime-wasi = "43.0.1"
wit-bindgen = { version = "0.57.1", default-features = false, features = ["macros", "macro-string"] }
