$(eval $(call addlib_s,appukwasmtime,$(CONFIG_APPUKWASMTIME)))

APPUKWASMTIME_TARGET_JSON := $(APPUKWASMTIME_BASE)/x86_64-unikraft.json

APPUKWASMTIME_CARGOFLAGS-y += \
	--target=$(APPUKWASMTIME_TARGET_JSON) \
	-Z build-std=core,alloc \
	-Z unstable-options \
	-Z json-target-spec

APPUKWASMTIME_RUSTCFLAGS-y += \
	-Zallow-features=alloc_error_handler,allocator_api,concat_idents,bench_black_box,global_asm,try_reserve

APPUKWASMTIME_SRCS-y += $(APPUKWASMTIME_BASE)/app/Cargo.toml
