[package]
name = "app-ukwasmtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
ukwasmtime = { path = "../.unikraft/libs/wasmtime/" }
ukrust = { path = "../.unikraft/unikraft/lib/ukrust/" }
httparse = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
